import { StyleSheet } from 'react-native';
import { spacing, radius } from '../../theme/colors';
import type { ColorScheme } from '../../theme/themes';

export const createStyles = (colors: ColorScheme) =>
  StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.lg,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: spacing.md,
  },
  headerText: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: 3,
    textShadowColor: colors.primary + '88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 16,
  },
  headerSubtitle: {
    fontSize: 13,
    color: colors.textMuted,
    marginTop: spacing.xs,
  },
  roundButton: {
    width: 40,
    height: 40,
    borderRadius: radius.full,
    backgroundColor: colors.surface + 'B3',
    borderWidth: 1,
    borderColor: colors.primary + '44',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 3,
  },
  roundButtonIcon: {
    fontSize: 18,
  },
  homeLink: {
    color: colors.primary,
    fontWeight: '800',
    letterSpacing: 1,
  },
  homeScroll: {
    flex: 1,
    marginTop: spacing.md,
  },
  homeContent: {
    paddingBottom: spacing.lg,
  },
  verifyBanner: {
    marginTop: spacing.sm,
    marginHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: 12,
    borderWidth: 1,
    gap: spacing.xs,
  },
  verifyBannerText: {
    fontSize: 13,
    lineHeight: 18,
  },
  verifyBannerActions: {
    flexDirection: 'row',
    gap: spacing.lg,
  },
  verifyBannerCta: {
    fontSize: 13,
    fontWeight: '700',
  },
  verifyBannerDismiss: {
    paddingVertical: 2,
  },
  homeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  homeTitle: {
    fontSize: 13,
    fontWeight: '900',
    color: colors.textMuted,
    letterSpacing: 5,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface + 'CC',
    borderWidth: 1,
    borderColor: colors.primary + '44',
    borderRadius: radius.full,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  statusPillDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginRight: spacing.xs,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.text,
    letterSpacing: 1,
  },
  cardGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: spacing.md,
    marginBottom: spacing.lg,
  },
  modeCard: {
    width: '48.4%',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.primary + '33',
    padding: spacing.md,
    overflow: 'hidden',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 12,
    elevation: 4,
  },
  modeCardPressed: {
    borderColor: colors.primary,
    shadowOpacity: 0.5,
    elevation: 8,
  },
  cardAccent: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 3,
  },
  cardIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    borderWidth: 1.5,
    backgroundColor: colors.surfaceAlt,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.sm,
  },
  cardIconText: {
    fontSize: 24,
  },
  cardLabel: {
    fontSize: 16,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: 1,
    marginBottom: 2,
  },
  cardSub: {
    fontSize: 11,
    lineHeight: 15,
    color: colors.textMuted,
    fontWeight: '600',
  },
  dialArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  arArea: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  trackArea: {
    flex: 1,
  },
  headingBlock: {
    marginTop: spacing.md,
    alignItems: 'center',
  },
  headingBig: {
    fontSize: 48,
    fontWeight: '900',
    color: colors.text,
    letterSpacing: 3,
    textShadowColor: colors.primary + '88',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 18,
  },
  headingCardinal: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primary,
    marginTop: spacing.xs,
    textShadowColor: colors.primary + '66',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  backBearing: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.text + 'aa',
    marginTop: spacing.xs,
    letterSpacing: 1,
  },
  levelHint: {
    fontSize: 14,
    color: colors.textMuted,
  },
  warningBox: {
    backgroundColor: colors.surface,
    borderColor: colors.north,
    borderWidth: 1,
    borderRadius: radius.md,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    marginBottom: spacing.md,
    alignItems: 'center',
  },
  warningText: {
    color: colors.north,
    textAlign: 'center',
    fontSize: 12,
    fontWeight: '600',
    marginVertical: 1,
  },
  celestialBar: {
    flexDirection: 'row',
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  celestialPill: {
    flex: 1,
    backgroundColor: colors.surface + 'B3',
    borderRadius: radius.full,
    borderWidth: 1,
    borderColor: colors.primary + '33',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  celestialText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textMuted,
    textAlign: 'center',
  },
  locationCard: {
    backgroundColor: colors.surface + 'B3',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.primary + '33',
    padding: spacing.md,
    marginBottom: spacing.lg,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.14,
    shadowRadius: 14,
    elevation: 3,
  },
  locationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  locationHeaderLeft: {
    flex: 1,
    marginRight: spacing.sm,
  },
  chevron: {
    fontSize: 18,
    fontWeight: '700',
    marginLeft: spacing.sm,
  },
  locSummary: {
    marginTop: spacing.xs,
  },
  locSummaryMain: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  locSummarySub: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    marginTop: 2,
  },
  placeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.surfaceAlt + 'B3',
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.primary + '2E',
  },
  placeName: {
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    color: colors.text,
    marginRight: spacing.sm,
  },
  cepChip: {
    backgroundColor: colors.primary,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  cepChipText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.background,
  },
  locationTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: 1,
  },
  locationActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  providerBadge: {
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderRadius: radius.full,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginRight: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
  },
  providerDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: spacing.xs,
  },
  providerText: {
    fontSize: 11,
    fontWeight: '700',
  },
  refreshButton: {
    width: 34,
    height: 34,
    borderRadius: radius.full,
    backgroundColor: colors.surfaceAlt,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshText: {
    fontSize: 18,
    color: colors.primary,
  },
  coordGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  coordCell: {
    width: '33.33%',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
  },
  coordCellDivider: {
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: colors.border,
  },
  coordRowDivider: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
  },
  coordLabel: {
    fontSize: 12,
    color: colors.textMuted,
  },
  coordValue: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginTop: 2,
  },
  locationError: {
    color: colors.danger,
    fontSize: 13,
  },
  locBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  locWaiting: {
    marginLeft: spacing.sm,
    fontSize: 13,
    color: colors.textMuted,
  },
});
