import { StyleSheet, type StyleProp, type ViewStyle } from 'react-native';
import { spacing, radius } from '../../theme/colors';
import type { ColorScheme } from '../../theme/themes';

export const rowDivider = (colors: ColorScheme): StyleProp<ViewStyle> => ({
  borderTopWidth: StyleSheet.hairlineWidth,
  borderTopColor: colors.border,
});

export const styles = StyleSheet.create({
backdrop: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.55)',
  justifyContent: 'flex-end',
},
card: {
  borderTopLeftRadius: radius.lg,
  borderTopRightRadius: radius.lg,
  padding: spacing.lg,
  paddingBottom: spacing.xl,
  maxHeight: '88%',
},
header: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: spacing.md,
},
title: {
  fontSize: 22,
  fontWeight: '800',
},
subtitle: {
  fontSize: 12,
  marginTop: 2,
},
closeButton: {
  width: 38,
  height: 38,
  borderRadius: radius.full,
  backgroundColor: 'transparent',
  borderWidth: 1,
  borderColor: '#00000022',
  alignItems: 'center',
  justifyContent: 'center',
},
closeText: {
  fontSize: 16,
},
sectionLabel: {
  fontSize: 12,
  fontWeight: '700',
  textTransform: 'uppercase',
  letterSpacing: 0.8,
  marginTop: spacing.md,
  marginBottom: spacing.sm,
  paddingLeft: spacing.xs,
},
gridRow: {
  flexDirection: 'row',
  flexWrap: 'wrap',
},
gridOption: {
  flexGrow: 1,
  flexBasis: '30%',
  minWidth: 96,
  marginRight: spacing.sm,
  marginBottom: spacing.sm,
  borderRadius: radius.lg,
  borderWidth: 1,
  paddingVertical: spacing.md,
  alignItems: 'center',
  justifyContent: 'center',
},
themeSwatch: {
  width: 30,
  height: 30,
  borderRadius: 9,
  alignItems: 'center',
  justifyContent: 'center',
  marginBottom: spacing.xs + 2,
},
themeSwatchDot: {
  width: 10,
  height: 10,
  borderRadius: 5,
},
gridLabel: {
  fontSize: 12,
  fontWeight: '700',
  textAlign: 'center',
},
groupCard: {
  borderRadius: radius.lg,
  borderWidth: 1,
  borderColor: '#00000018',
},
groupRow: {
  flexDirection: 'row',
  alignItems: 'center',
  padding: spacing.md,
},
rowCol: {
  flexDirection: 'column',
  alignItems: 'stretch',
},
calRow: {
  flexDirection: 'row',
  alignItems: 'center',
},
iconChip: {
  width: 40,
  height: 40,
  borderRadius: radius.md,
  alignItems: 'center',
  justifyContent: 'center',
  marginRight: spacing.md,
},
iconChipText: {
  fontSize: 18,
},
groupText: {
  flex: 1,
},
groupLabel: {
  fontSize: 15,
  fontWeight: '700',
},
groupSub: {
  fontSize: 12,
  marginTop: 2,
  lineHeight: 16,
},
radio: {
  width: 20,
  height: 20,
  borderRadius: 10,
  borderWidth: 2,
  alignItems: 'center',
  justifyContent: 'center',
  marginLeft: spacing.sm,
},
radioInner: {
  width: 12,
  height: 12,
  borderRadius: 6,
},
statusDot: {
  width: 10,
  height: 10,
  borderRadius: 5,
  marginLeft: spacing.sm,
},
switchTrack: {
  width: 44,
  height: 26,
  borderRadius: 13,
  padding: 2,
  flexDirection: 'row',
  alignItems: 'center',
  marginLeft: spacing.sm,
},
switchTrackOn: {
  justifyContent: 'flex-end',
},
switchTrackOff: {
  justifyContent: 'flex-start',
},
switchKnob: {
  width: 22,
  height: 22,
  borderRadius: 11,
},
stepperRow: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: spacing.md,
  justifyContent: 'center',
},
stepperButton: {
  width: 36,
  height: 36,
  borderRadius: radius.sm,
  alignItems: 'center',
  justifyContent: 'center',
},
stepperText: {
  fontSize: 20,
  fontWeight: '800',
},
stepperValue: {
  fontSize: 16,
  fontWeight: '800',
  marginHorizontal: spacing.md,
  minWidth: 64,
  textAlign: 'center',
},
suggestButton: {
  marginTop: spacing.sm,
  paddingVertical: spacing.xs,
  alignItems: 'center',
},
suggestText: {
  fontSize: 12,
  fontWeight: '700',
  textDecorationLine: 'underline',
},
chevron: {
  fontSize: 22,
  fontWeight: '700',
  marginLeft: spacing.sm,
},
pinOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: 'rgba(0,0,0,0.45)',
  paddingHorizontal: spacing.xl,
},
pinCard: {
  width: '100%',
  maxWidth: 320,
  borderRadius: radius.lg,
  borderWidth: 1,
  borderColor: '#00000018',
  padding: spacing.xl,
  alignItems: 'center',
},
pinTitle: {
  fontSize: 18,
  fontWeight: '800',
  textAlign: 'center',
},
pinSub: {
  fontSize: 12,
  marginTop: spacing.xs,
  marginBottom: spacing.md,
  textAlign: 'center',
  lineHeight: 16,
},
pinInput: {
  width: 160,
  height: 52,
  borderWidth: 1,
  borderRadius: radius.md,
  fontSize: 26,
  letterSpacing: 14,
  fontWeight: '800',
  textAlign: 'center',
},
pinDots: {
  flexDirection: 'row',
  marginTop: spacing.md,
},
pinDot: {
  width: 10,
  height: 10,
  borderRadius: 5,
  marginHorizontal: 6,
},
pinErrorText: {
  fontSize: 12,
  fontWeight: '700',
  marginTop: spacing.md,
  textAlign: 'center',
},
pinErrorSpacer: {
  marginTop: spacing.md,
  height: 16,
},
pinCancel: {
  marginTop: spacing.md,
  padding: spacing.sm,
},
pinCancelText: {
  fontSize: 14,
  fontWeight: '700',
  textTransform: 'uppercase',
  letterSpacing: 0.6,
},
importCard: {
  width: '100%',
  maxWidth: 360,
  borderRadius: radius.lg,
  borderWidth: 1,
  borderColor: '#00000018',
  padding: spacing.lg,
},
importInput: {
  width: '100%',
  height: 140,
  borderWidth: 1,
  borderRadius: radius.md,
  padding: spacing.md,
  fontSize: 13,
  marginTop: spacing.sm,
  fontFamily: 'monospace',
},
importActions: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'flex-end',
  marginTop: spacing.sm,
},
restoreButton: {
  paddingHorizontal: spacing.lg,
  paddingVertical: spacing.sm,
  borderRadius: radius.md,
  marginLeft: spacing.sm,
},
restoreButtonText: {
  color: '#000',
  fontSize: 14,
  fontWeight: '800',
},
});
